In [26]:
import numpy as np
import pandas as pd
# import matplotlib as mpl
# import seaborn as sbs

y = np.random.randint(1,5,5)
y
coloumn = ['sl_no','acount_no','pin','ifsc','address','plot_no','pan_no','vter_no','school','college','stream','medical history','dob','profession','contact no','adiction']
len(coloumn)
sl_no = np.linspace(1,100,100,np.int64)
acount_no = np.random.normal(500000000,200000000,100)
acount_no = np.int64(acount_no)
a = np.random.randint(1,100,55)
a
for i in a:
    acount_no[i] = 000000000
acount_no



array([497968551,         0, 400263525,         0, 566350038,         0,
       206803972,         0, 648646614,         0, 809172683,         0,
               0, 588379875,         0, 502031651,         0,         0,
       537913794, 158303686, 600054827, 582001100,         0,         0,
       403977398, 276109703, 770198276, 465784418,         0,         0,
       884124893, 541474470, 570995746,         0,         0, 212639464,
               0, 100429027, 485523611, 556107699,         0,         0,
       700082184,         0,         0,         0, 743162242, 726491472,
       685666364,         0, 493075021, 488784604, 700864705, 304076737,
       240789310, 832299941, 814982722,         0, 365526082,   4482628,
               0, 442583869, 636656387, 675493162, 736824569, 564169896,
       610953971, 856962612,         0,         0, 541608236, 384254924,
       254628861, 429442463,         0, 360032261,         0, 136477231,
               0,         0,         0,         0, 

In [25]:
pin = np.random.normal(5000,2000,100)
pin = np.int64(pin)
b = np.random.randint(1,100,86)
b
for i in b:
    pin[i] = 000000000
pin

array([3514, 3320, 6187,    0, 3523,    0,    0,    0,    0, 6046, 3172,
       1677,    0, 7404, 6783, 2810, 4726, 4598, 5059, 4031, 5850,    0,
       5354, 2342, 7355,    0,    0, 8423,    0, 3904, 5023,    0,    0,
          0, 4683,    0,    0,    0,    0, 5652,    0, 2363, 7373, 6242,
          0,    0,    0, 2817, 4128, 4785,    0,    0,    0,    0, 3279,
          0,    0, 2720, 2910, 4682,    0,    0, 4126, 7503, 4506, 6277,
          0, 6652, 3983, 3421, 5378,    0, 2223, 5099, 5059,    0,    0,
       3728, 4374, 5163,    0,    0,    0,    0, 2393,    0,    0, 7763,
       4037, 6650,  374,    0, 3413, 2751,    0,    0,    0, 5753,    0,
          0])

In [53]:
rifsc = np.random.randint(000000,999999,20)
ifsc = np.zeros(100,np.int64)
ifsc
c = np.random.randint(1,100,40)
for i in c:
    if i>19:
        j = np.random.randint(0,20)
    else:
        j = i
    ifsc[i] = rifsc[j]
ifsc

array([     0, 660120,      0, 198615,      0,      0,      0,      0,
            0,      0, 215861, 636805,      0, 157510,      0,      0,
       897448,  19442,      0,      0, 421726,      0,      0,      0,
            0, 198615, 944560,      0, 198615,      0,      0, 157510,
       664218,      0,      0, 153639,      0, 897448,      0,      0,
       188457,      0,      0, 157510, 157510,      0, 944560, 260244,
            0,      0, 260244,      0,      0,      0,      0,      0,
       250483,      0,      0,      0,      0,      0,      0, 421726,
            0, 215861,      0,      0, 250483, 188457,      0, 664218,
            0,      0,      0, 221634,      0,      0,      0,      0,
            0,  19442, 421726,      0,      0,      0, 215861, 221634,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0])

In [38]:
acount_no = pd.Series(acount_no)
pin = pd.Series(pin)
frame = {'acount_no':acount_no,'pin':pin,'ifsc':ifsc}
data = pd.DataFrame(frame)
data
data.to_excel("sample_data.xlsx")

In [76]:
address = {'1':'west','2':'south','3':'north','4':'east','5':'north_east','6':'north_west','7':'south_east','8':'south_west'}
address

{'1': 'west',
 '2': 'south',
 '3': 'north',
 '4': 'east',
 '5': 'north_east',
 '6': 'north_west',
 '7': 'south_east',
 '8': 'south_west'}

In [77]:
addresss = np.random.normal(4.5,1.5,8)
addresss = np.int64(addresss)
addresss


array([4, 4, 2, 3, 4, 3, 1, 2])

In [78]:
ad = np.zeros(100,np.int64)
ad
no = 75
i = 0
while i<no:
    ad[np.random.randint(0,99)] = addresss[np.random.randint(0,7)]
    i+=1
ad

array([0, 4, 0, 0, 0, 3, 0, 0, 0, 4, 2, 0, 1, 2, 3, 3, 4, 0, 0, 4, 0, 0,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 4, 2, 1, 1, 4, 0, 0, 0, 3, 0, 0, 3, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 1, 0, 3, 3, 3, 4, 3, 0, 3, 1, 2, 0,
       4, 0, 4, 2, 0, 0, 3, 4, 0, 0, 4, 0, 0, 2, 4, 0, 0, 3, 4, 1, 0, 3,
       4, 0, 2, 0, 3, 3, 4, 4, 1, 4, 4, 0])

In [92]:
l = []
for i in ad:
    if i == 0:
        l.append(0)
    else:
        l.append(address[str(i)])
l
# address['1']
location = pd.Series(l)
location


0        0
1     east
2        0
3        0
4        0
      ... 
95    east
96    west
97    east
98    east
99       0
Length: 100, dtype: object

In [94]:
data['location'] = location
data.to_excel("")
data

acount_no   pin    ifsc location
0   497968551  3514  699184        0
1           0  3320  800575     east
2   400263525  6187   57170        0
3           0     0  152109        0
4   566350038  3523       0        0
..        ...   ...     ...      ...
95  458832009     0       0     east
96  518087966     0  637694     west
97          0  5753       0     east
98  381346123     0       0     east
99          0     0  499313        0

[100 rows x 4 columns]